### PR TITLE
3.2 compatibility

### PR DESCRIPTION
**Pull request by chillu**
Haven't extensively tested, but tests are passing on latest master. You'll need to decide on how to handle branching (a 2.0 branch for 3.1 compat?), and update the travis.yml and README accordingly.

### CODE REVIEW

**Comment by tractorcow** [comment]
@chillu shall we add PHP 5.6, and maybe instead of testing master, just test 3, 3.1 and 3.2 branches? With semver we don't need to support more than one major version per branch.

We can probably forget about 3.0 for now, but @silverstripe-australia can make a new branch if they want to keep it separate. :D

**Comment by chillu** [comment]
Rebased, added 5.6 and 3.* builds as suggested, removed master build. Agree that creating a 3.0 compatible branch in this module is probably lower priority.

**Comment by tractorcow** [comment]
I've tagged at 2.2.0 to signify the bump of the lower version constraint to 3.1 :D

**Comment by nyeholt** [comment]
Yep, not concerned about a 3.0 module compat branch :)

**Pull request merged**
