### PR TITLE
SS4 Compatiblity

### PR DESCRIPTION
**Pull request by JackOconnor21**
An upgrade to allow this module to work with ss4.

### CODE REVIEW

**Comment by JackOconnor21** [comment]
This fails checks due to the travis.yml file. Please review changes disregarding check.

**Comment by nyeholt** [comment]
Hi Jack, can you change the vendor prefix to SilverStripeAustralia\? Otherwise it's good to go.

**Comment by JackOconnor21** [comment]
@nyeholt just to clarify, are you aware the gridfieldextensions module PR I created (using SilverStripe\ ) has already been merged? I assume for all related modules you guys would want consistency, whether that be SilverStripe or SilverStripeAustralia. Please let me know and I can proceed as requested, thanks :)

**Comment by nyeholt** [comment]
Hi Jack - yep, saw that go through after the fact :)

**Comment by dhensby** [comment]
A good rule of thumb is that the base namespace should match the package vendor. In this case it is `silverstripe` (see https://github.com/silverstripe-australia/silverstripe-multivaluefield/blob/master/composer.json#L2)

There may be other packages in the `silverstripe-australia` vendor name and those should/could be `SilverStripeAustralia`

**Comment by nyeholt** [comment]
@dhensby yes - the "silverstripe/" vendor prefix was added as part of the very first move to composer where many SSAU developed modules weren't properly identified. Given the overall disruptive changes going on with SS4 it's probably as good a time as any for us to properly re-align our modules into their proper vendor name(space); we've got a bit of housekeeping to do on our side to prioritise those that need changing, get those updated to SS4, and make the subsequent releases all together (while trying to avoid  downstream disruption as much as possible!)

**Comment by JackOconnor21** [comment]
Ok no problem, I have updated the namespacing, if someone could also check my grid field extensions PR i'm about to make and accept that too, that would be appreciated. Thanks.

**Comment by nyeholt** [comment]
Looks like it's needing the MultiValueField field type aliased to the class - see https://github.com/silverstripe/silverstripe-framework/blob/master/_config/model.yml

```yml
---
Name: mvfieldtypes
---
SilverStripe\Core\Injector\Injector:
  MultiValueField:
    class: SilverStripeAustralia\MultiValueField\Fields\MultiValueField
```

**Comment by nyeholt** [comment]
I've merged this through, but there were several things I needed to fix on the way in. It's also in a 'pretty much broken' state, as entered values don't save, nor do the fields work correctly in the UI. However it will at least provide an installation target for dependent modules...

**Pull request merged**
