### PR TITLE
MNT Standardise modules

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/570

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
There's still a .scrutinizer.yml file here.

**Comment by emteknetnz** [comment]
I spelt it wrong in my script :/ `.scrutinzer.yml` - missing an `i`

**Comment by emteknetnz** [comment]
Fixed

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Need to update workflows to not use `startsWith` syntax

**Comment by emteknetnz** [comment]
Updated

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Keepalive also needs the `startsWith` syntax updated.

**Comment by emteknetnz** [comment]
Updated

**Review by GuySartorelli — APPROVED** [review]
MOG

**Pull request merged**
